In [61]:
from PIL import Image
import numpy as np
import cv2


In [62]:
# Load the host and watermark images
hr_image = Image.open("high_resolution_image.jpg")
wm_image = Image.open("./ravenLogo.jpg")

# Resize the watermark image to the same size as the host image
wm_image_resized = wm_image.resize(hr_image.size)

# Convert both images to grayscale
hr_image = hr_image.convert("L")
wm_image_resized = wm_image_resized.convert("L")


In [63]:
# hr_image = cv2.imread('high_resolution_image.jpg', cv2.IMREAD_GRAYSCALE)
# wm_image = cv2.imread('./download.png', cv2.IMREAD_GRAYSCALE)


In [64]:
# hr_image = cv2.imread('high_resolution_image.jpg')
# wm_image = cv2.imread('./download.png')


In [65]:
# wm_image_resized = cv2.resize(wm_image, hr_image.shape[::-1])

In [66]:
U_hr, sigma_hr, V_hr = np.linalg.svd(hr_image)

KeyboardInterrupt: 

In [ ]:
U_hr

array([[ 0.01048138,  0.01586544,  0.01058289, ..., -0.02016765,
         0.01017384, -0.01096529],
       [ 0.01049814,  0.01588426,  0.01053788, ...,  0.0561238 ,
        -0.01881205, -0.01012581],
       [ 0.01052205,  0.01589693,  0.01051243, ..., -0.01547944,
         0.01076705,  0.02154981],
       ...,
       [ 0.00316736,  0.01004396, -0.00239396, ..., -0.01102048,
         0.01805149,  0.0211272 ],
       [ 0.00316531,  0.01013575, -0.00301917, ...,  0.01078797,
        -0.0224164 ,  0.0095271 ],
       [ 0.00316252,  0.01017166, -0.00318538, ..., -0.0040119 ,
         0.02046394, -0.01273782]])

In [ ]:
sigma_hr

array([3.94059786e+05, 8.62034800e+04, 4.28296783e+04, ...,
       6.78103592e+00, 6.71517895e+00, 6.66104808e+00])

In [ ]:
V_hr

array([[ 6.16607823e-03,  6.16918847e-03,  6.17463641e-03, ...,
         3.95141258e-03,  3.95400788e-03,  3.95059285e-03],
       [-6.58376375e-03, -6.53393161e-03, -6.49567229e-03, ...,
         9.56896267e-03,  9.57393587e-03,  9.54534473e-03],
       [ 4.28410374e-03,  4.18640186e-03,  4.11677890e-03, ...,
         8.86172377e-03,  8.88168188e-03,  8.87935101e-03],
       ...,
       [ 1.59231363e-03, -6.85560395e-03,  1.71597659e-03, ...,
         5.74650007e-01, -1.43948525e-01, -8.71123739e-02],
       [-3.03242332e-03,  1.24028335e-02, -5.58871039e-03, ...,
        -1.40842345e-01,  5.25180858e-01, -1.54422566e-01],
       [-3.53734728e-04,  1.95760313e-02, -1.31335894e-02, ...,
        -8.78492097e-02, -1.58914596e-01,  4.92485754e-01]])

In [ ]:
U_wm, sigma_wm, V_wm = np.linalg.svd(wm_image_resized)

In [ ]:
U_wm

array([[ 0.01928185,  0.00605473,  0.00802464, ...,  0.0678824 ,
         0.10627277, -0.1544874 ],
       [ 0.01928185,  0.00605473,  0.00802464, ...,  0.00225156,
         0.00135001,  0.00161912],
       [ 0.01928185,  0.00605473,  0.00802464, ..., -0.13639   ,
        -0.14160791,  0.07312868],
       ...,
       [ 0.01928185,  0.00605473,  0.00802464, ..., -0.01847901,
         0.01124279, -0.00632762],
       [ 0.01928185,  0.00605473,  0.00802464, ...,  0.01471103,
        -0.0347995 ,  0.00156111],
       [ 0.01928185,  0.00605473,  0.00802464, ...,  0.01473661,
        -0.0347757 ,  0.00152805]])

In [ ]:
sigma_wm

array([9.39330057e+05, 2.88628913e+04, 2.61896397e+04, ...,
       4.92166993e-11, 3.03318843e-11, 9.03679547e-12])

In [ ]:
V_wm

array([[ 1.43464642e-02,  1.43464642e-02,  1.43464642e-02, ...,
         1.43464642e-02,  1.43464642e-02,  1.43464642e-02],
       [-7.15168673e-04, -7.15168673e-04, -7.15168673e-04, ...,
        -7.15168673e-04, -7.15168673e-04, -7.15168673e-04],
       [-7.53372307e-03, -7.53372307e-03, -7.53372307e-03, ...,
        -7.53372307e-03, -7.53372307e-03, -7.53372307e-03],
       ...,
       [-1.88435089e-04,  3.64382199e-03,  5.85795559e-03, ...,
         8.76474691e-01, -1.08082610e-01,  1.64127010e-02],
       [-1.17657768e-04,  3.75853293e-03,  7.47456479e-03, ...,
        -1.08171989e-01,  8.04115247e-01, -7.98931604e-02],
       [ 1.09789753e-04, -7.98163671e-04, -7.31382208e-03, ...,
         1.47661015e-02, -8.08975733e-02,  8.91553900e-01]])

In [ ]:
alpha = 0.6
sigma_hr_mod = sigma_hr + alpha * sigma_wm

In [ ]:
sigma_hr_mod

array([9.57657820e+05, 1.03521215e+05, 5.85434621e+04, ...,
       6.78103592e+00, 6.71517895e+00, 6.66104808e+00])

In [ ]:
hr_image_mod = np.dot(U_hr[:, :sigma_hr_mod.shape[0]], np.dot(np.diag(sigma_hr_mod), V_hr[:sigma_hr_mod.shape[0],:]))
hr_image_mod

array([[57.15444456, 57.16265146, 56.16061459, ..., 69.11850106,
        69.10770374, 68.03166083],
       [57.18265103, 56.15990984, 56.1585609 , ..., 69.14193355,
        68.12338714, 68.06400936],
       [57.20068055, 56.1703814 , 56.17762905, ..., 68.17361288,
        68.17393658, 67.1207365 ],
       ...,
       [ 8.87976713,  9.02461511,  9.14234795, ..., 14.00217746,
        13.94622359, 13.92079315],
       [ 8.82783366,  9.00535652,  9.13732384, ..., 14.14664224,
        14.09494624, 14.06141679],
       [ 8.6628953 ,  8.84360943,  9.02375324, ..., 14.18303731,
        14.13505932, 14.115118  ]])

In [ ]:
hr_image_mod = cv2.normalize(hr_image_mod, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
hr_image_mod


array([[24, 24, 23, ..., 29, 29, 28],
       [24, 23, 23, ..., 29, 28, 28],
       [24, 23, 23, ..., 28, 28, 28],
       ...,
       [ 3,  3,  3, ...,  5,  5,  5],
       [ 3,  3,  3, ...,  5,  5,  5],
       [ 3,  3,  3, ...,  5,  5,  5]], dtype=uint8)

In [ ]:
img1 = Image.fromarray(hr_image_mod)
img1.show()

In [ ]:
img1.save('output_image.png')


# Embedded

In [ ]:
U_hr_mod1, sigma_hr_mod1, V_hr_mod1 = np.linalg.svd(hr_image_mod)

In [ ]:
U_hr1, sigma_hr1, V_hr1 = np.linalg.svd(hr_image)

In [ ]:
U_wm1, sigma_wm1, V_wm1 = np.linalg.svd(np.zeros_like(hr_image))
U_wm1, sigma_wm1, V_wm1


(array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]))

In [ ]:
sigma_wm_mod = (sigma_hr_mod - sigma_hr) / alpha

In [ ]:
sigma_wm_mod

array([9.39330057e+05, 2.88628913e+04, 2.61896397e+04, ...,
       4.92169268e-11, 3.03312930e-11, 9.03721542e-12])

In [ ]:
watermark = np.dot(U_wm[:, :sigma_wm_mod.shape[0]], np.dot(np.diag(sigma_wm_mod), V_wm[:sigma_wm_mod.shape[0],:]))

In [ ]:
img=Image.fromarray(watermark)
img.show()